spring:
  datasource:
    url: jdbc:postgresql://polar-postgres:5432/polardb_catalog
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://polar-keycloak/realms/PolarBookshop
