spring:
  data:
    redis:
      host: polar-redis
      port: 6379
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://polar-keycloak:8080/realms/PolarBookshop
